POSTGRES_HOST=judge0-db
POSTGRES_PORT=5432
POSTGRES_DB=judge0
POSTGRES_USER=judge0
POSTGRES_PASSWORD=judge0

REDIS_HOST=judge0-redis
REDIS_PORT=6379
REDIS_PASSWORD=judge0

RAILS_ENV=production
RAILS_MAX_THREADS=2
SECRET_KEY_BASE=pp1-local-judge0-secret-key-base-change-for-production

ENABLE_WAIT_RESULT=true
ENABLE_COMPILER_OPTIONS=true
ENABLE_COMMAND_LINE_ARGUMENTS=true
ENABLE_SUBMISSION_DELETE=false

MAX_QUEUE_SIZE=100
CPU_TIME_LIMIT=5
CPU_EXTRA_TIME=1
WALL_TIME_LIMIT=10
MEMORY_LIMIT=256000
STACK_LIMIT=64000
MAX_PROCESSES_AND_OR_THREADS=60
ENABLE_NETWORK=false
