export function buildReactSandboxHTML(jsxCode: string): string {
  const encoded = JSON.stringify(jsxCode);
  return [
    '<!DOCTYPE html><html><head><meta charset="UTF-8">',
    '<link href="https://cdn.jsdelivr.net/npm/tailwindcss@2/dist/tailwind.min.css" rel="stylesheet">',
    '<style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:-apple-system,BlinkMacSystemFont,sans-serif;background:#fff}#root{width:100%;min-height:100px}.sandbox-error{padding:20px;color:#dc2626;font-size:13px;font-family:monospace;background:#fef2f2;border:1px solid #fecaca;border-radius:8px;margin:12px;white-space:pre-wrap}.sandbox-loading{display:flex;align-items:center;justify-content:center;gap:10px;padding:40px;color:#6b7280;font-size:13px}.spinner{width:18px;height:18px;border:2px solid #e5e7eb;border-top-color:#6d5cff;border-radius:50%;animation:spin .8s linear infinite}@keyframes spin{to{transform:rotate(360deg)}}</style>',
    '</head><body><div id="root"><div class="sandbox-loading"><div class="spinner"></div><span>加载依赖库...</span></div></div>',
    '<script>',
    'var S=[',
    '{u:"https://cdn.jsdelivr.net/npm/react@18/umd/react.production.min.js",r:1,n:"React",a:function(){window.React=React}},',
    '{u:"https://cdn.jsdelivr.net/npm/react-dom@18/umd/react-dom.production.min.js",r:1,n:"ReactDOM",a:function(){window.ReactDOM=ReactDOM}},',
    '{u:"https://cdn.jsdelivr.net/npm/@babel/standalone@7/babel.min.js",r:1,n:"Babel"},',
    '{u:"https://cdn.jsdelivr.net/npm/prop-types@15/prop-types.min.js",r:0,n:"PropTypes",a:function(){window.PropTypes=PropTypes}},',
    '{u:"https://cdn.jsdelivr.net/npm/recharts@2.12.7/umd/Recharts.js",r:0,n:"Recharts"}',
    '];var lc=0;',
    'function L(i){if(i>=S.length){R();return}var o=S[i],s=document.createElement("script");s.src=o.u;',
    's.onload=function(){lc++;if(o.a)try{o.a()}catch(e){}var sp=document.querySelector(".sandbox-loading span");if(sp)sp.textContent=o.n+" \\u2713 ("+lc+"/"+S.length+")";L(i+1)};',
    's.onerror=function(){if(o.r){document.getElementById("root").innerHTML="<div class=sandbox-error>加载失败："+o.n+"</div>";rh()}else L(i+1)};',
    'document.head.appendChild(s)}',
    '',
    'function R(){',
    'var reg={"react":Object.assign({},React,{default:React,useState:React.useState,useEffect:React.useEffect,useRef:React.useRef,useMemo:React.useMemo,useCallback:React.useCallback,useReducer:React.useReducer,useContext:React.useContext,createContext:React.createContext,Fragment:React.Fragment,createElement:React.createElement,forwardRef:React.forwardRef,memo:React.memo}),',
    '"react-dom":Object.assign({default:ReactDOM},ReactDOM),"react-dom/client":Object.assign({default:ReactDOM},ReactDOM)};',
    'if(typeof Recharts!=="undefined")try{reg["recharts"]=Object.assign({default:Recharts},Recharts)}catch(e){}',
    'if(typeof PropTypes!=="undefined")reg["prop-types"]=Object.assign({default:PropTypes},PropTypes);',
    'function req(m){var mod=reg[m];if(!mod){if(typeof Proxy!=="undefined")return new Proxy({},{get:function(t,p){if(p==="__esModule")return true;return function(props){return React.createElement("span",null,props&&props.children||"")}}});return{}}return mod}',
    'try{',
    'var src=' + encoded + ';',
    'var compiled=Babel.transform(src,{presets:["react"],plugins:["transform-modules-commonjs"],filename:"c.jsx"}).code;',
    'var me={};var mo={exports:me};',
    'new Function("require","module","exports","React","ReactDOM",compiled)(req,mo,me,React,ReactDOM);',
    'var C=mo.exports.default||mo.exports;',
    'if(typeof C!=="function")throw new Error("未找到 export default 的组件");',
    'var root=document.getElementById("root");',
    'if(ReactDOM.createRoot)ReactDOM.createRoot(root).render(React.createElement(C));',
    'else ReactDOM.render(React.createElement(C),root);',
    'setTimeout(rh,100);setTimeout(rh,500);setTimeout(rh,1500);setTimeout(rh,3000)',
    '}catch(err){document.getElementById("root").innerHTML="<div class=sandbox-error>渲染错误：\\n\\n"+esc(err.message)+"</div>";rh()}}',
    '',
    'function esc(s){return s.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;")}',
    'function rh(){var h=Math.max(document.body.scrollHeight||0,document.body.offsetHeight||0,document.documentElement.scrollHeight||0,document.documentElement.offsetHeight||0);window.parent.postMessage({type:"sandbox-height",height:h},"*")}',
    'window.onerror=function(msg){var r=document.getElementById("root");if(r&&!r.querySelector(".sandbox-error"))r.innerHTML="<div class=sandbox-error>运行时错误：\\n"+esc(String(msg))+"</div>";rh()};',
    'setTimeout(function(){if(document.querySelector(".sandbox-loading")){document.getElementById("root").innerHTML="<div class=sandbox-error>加载超时</div>";rh()}},15000);',
    'L(0);',
    '<' + '/script></body></html>',
  ].join('\n');
}
