import prisma from './db';

const statements = [
  `CREATE TABLE IF NOT EXISTS "CourseKnowledgeConcept" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "conceptKey" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "description" TEXT NOT NULL DEFAULT '',
    "aliasesJson" TEXT NOT NULL DEFAULT '[]',
    "category" TEXT NOT NULL DEFAULT 'concept',
    "difficulty" REAL NOT NULL DEFAULT 0.5,
    "status" TEXT NOT NULL DEFAULT 'active',
    "source" TEXT NOT NULL DEFAULT 'system',
    "evidenceJson" TEXT NOT NULL DEFAULT '{}',
    "activationScore" REAL NOT NULL DEFAULT 0,
    "lastActivatedAt" DATETIME,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "workspaceId" TEXT NOT NULL,
    CONSTRAINT "CourseKnowledgeConcept_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace" ("id") ON DELETE CASCADE ON UPDATE CASCADE
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "CourseKnowledgeConcept_workspaceId_conceptKey_key" ON "CourseKnowledgeConcept"("workspaceId", "conceptKey")`,
  `CREATE INDEX IF NOT EXISTS "CourseKnowledgeConcept_workspaceId_status_updatedAt_idx" ON "CourseKnowledgeConcept"("workspaceId", "status", "updatedAt")`,
  `CREATE INDEX IF NOT EXISTS "CourseKnowledgeConcept_workspaceId_activationScore_idx" ON "CourseKnowledgeConcept"("workspaceId", "activationScore")`,
  `CREATE TABLE IF NOT EXISTS "CourseKnowledgeConceptTag" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "label" TEXT NOT NULL,
    "normalizedLabel" TEXT NOT NULL,
    "state" TEXT NOT NULL DEFAULT 'candidate',
    "sourcesJson" TEXT NOT NULL DEFAULT '[]',
    "rationale" TEXT NOT NULL DEFAULT '',
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "workspaceId" TEXT NOT NULL,
    "conceptId" TEXT NOT NULL,
    CONSTRAINT "CourseKnowledgeConceptTag_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "CourseKnowledgeConceptTag_conceptId_fkey" FOREIGN KEY ("conceptId") REFERENCES "CourseKnowledgeConcept" ("id") ON DELETE CASCADE ON UPDATE CASCADE
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "CourseKnowledgeConceptTag_workspaceId_conceptId_normalizedLabel_key" ON "CourseKnowledgeConceptTag"("workspaceId", "conceptId", "normalizedLabel")`,
  `CREATE INDEX IF NOT EXISTS "CourseKnowledgeConceptTag_workspaceId_state_normalizedLabel_idx" ON "CourseKnowledgeConceptTag"("workspaceId", "state", "normalizedLabel")`,
  `CREATE INDEX IF NOT EXISTS "CourseKnowledgeConceptTag_conceptId_state_idx" ON "CourseKnowledgeConceptTag"("conceptId", "state")`,
  `CREATE TABLE IF NOT EXISTS "CourseKnowledgeRelation" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "relationType" TEXT NOT NULL,
    "weight" REAL NOT NULL DEFAULT 0.6,
    "confidence" REAL NOT NULL DEFAULT 0.55,
    "source" TEXT NOT NULL DEFAULT 'system',
    "evidenceJson" TEXT NOT NULL DEFAULT '{}',
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "workspaceId" TEXT NOT NULL,
    "fromConceptId" TEXT NOT NULL,
    "toConceptId" TEXT NOT NULL,
    CONSTRAINT "CourseKnowledgeRelation_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "CourseKnowledgeRelation_fromConceptId_fkey" FOREIGN KEY ("fromConceptId") REFERENCES "CourseKnowledgeConcept" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "CourseKnowledgeRelation_toConceptId_fkey" FOREIGN KEY ("toConceptId") REFERENCES "CourseKnowledgeConcept" ("id") ON DELETE CASCADE ON UPDATE CASCADE
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "CourseKnowledgeRelation_workspaceId_fromConceptId_toConceptId_relationType_key" ON "CourseKnowledgeRelation"("workspaceId", "fromConceptId", "toConceptId", "relationType")`,
  `CREATE INDEX IF NOT EXISTS "CourseKnowledgeRelation_workspaceId_relationType_idx" ON "CourseKnowledgeRelation"("workspaceId", "relationType")`,
  `CREATE INDEX IF NOT EXISTS "CourseKnowledgeRelation_toConceptId_relationType_idx" ON "CourseKnowledgeRelation"("toConceptId", "relationType")`,
  `CREATE TABLE IF NOT EXISTS "CourseKnowledgeBinding" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "bindingType" TEXT NOT NULL,
    "targetType" TEXT NOT NULL,
    "targetId" TEXT NOT NULL,
    "role" TEXT NOT NULL DEFAULT 'supports',
    "strength" REAL NOT NULL DEFAULT 0.55,
    "confidence" REAL NOT NULL DEFAULT 0.55,
    "evidenceJson" TEXT NOT NULL DEFAULT '{}',
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "workspaceId" TEXT NOT NULL,
    "conceptId" TEXT NOT NULL,
    "fileObjectId" TEXT,
    "workbenchId" TEXT,
    "goalId" TEXT,
    CONSTRAINT "CourseKnowledgeBinding_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "CourseKnowledgeBinding_conceptId_fkey" FOREIGN KEY ("conceptId") REFERENCES "CourseKnowledgeConcept" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "CourseKnowledgeBinding_fileObjectId_fkey" FOREIGN KEY ("fileObjectId") REFERENCES "FileSystemObject" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "CourseKnowledgeBinding_workbenchId_fkey" FOREIGN KEY ("workbenchId") REFERENCES "Workbench" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "CourseKnowledgeBinding_goalId_fkey" FOREIGN KEY ("goalId") REFERENCES "LearningGoal" ("id") ON DELETE SET NULL ON UPDATE CASCADE
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "CourseKnowledgeBinding_workspaceId_conceptId_targetType_targetId_role_key" ON "CourseKnowledgeBinding"("workspaceId", "conceptId", "targetType", "targetId", "role")`,
  `CREATE INDEX IF NOT EXISTS "CourseKnowledgeBinding_workspaceId_targetType_targetId_idx" ON "CourseKnowledgeBinding"("workspaceId", "targetType", "targetId")`,
  `CREATE INDEX IF NOT EXISTS "CourseKnowledgeBinding_conceptId_bindingType_idx" ON "CourseKnowledgeBinding"("conceptId", "bindingType")`,
  `CREATE TABLE IF NOT EXISTS "CourseKnowledgeExercise" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "exerciseKey" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "prompt" TEXT NOT NULL DEFAULT '',
    "exerciseType" TEXT NOT NULL DEFAULT 'question',
    "difficulty" REAL NOT NULL DEFAULT 0.5,
    "answerJson" TEXT NOT NULL DEFAULT '{}',
    "explanation" TEXT NOT NULL DEFAULT '',
    "source" TEXT NOT NULL DEFAULT 'ai_kg_extraction',
    "evidenceJson" TEXT NOT NULL DEFAULT '{}',
    "status" TEXT NOT NULL DEFAULT 'active',
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "workspaceId" TEXT NOT NULL,
    "fileObjectId" TEXT,
    CONSTRAINT "CourseKnowledgeExercise_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "CourseKnowledgeExercise_fileObjectId_fkey" FOREIGN KEY ("fileObjectId") REFERENCES "FileSystemObject" ("id") ON DELETE SET NULL ON UPDATE CASCADE
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "CourseKnowledgeExercise_workspaceId_exerciseKey_key" ON "CourseKnowledgeExercise"("workspaceId", "exerciseKey")`,
  `CREATE INDEX IF NOT EXISTS "CourseKnowledgeExercise_workspaceId_status_updatedAt_idx" ON "CourseKnowledgeExercise"("workspaceId", "status", "updatedAt")`,
  `CREATE INDEX IF NOT EXISTS "CourseKnowledgeExercise_fileObjectId_idx" ON "CourseKnowledgeExercise"("fileObjectId")`,
  `CREATE TABLE IF NOT EXISTS "CourseKnowledgeExerciseBinding" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "role" TEXT NOT NULL DEFAULT 'assesses',
    "strength" REAL NOT NULL DEFAULT 0.65,
    "confidence" REAL NOT NULL DEFAULT 0.65,
    "evidenceJson" TEXT NOT NULL DEFAULT '{}',
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "workspaceId" TEXT NOT NULL,
    "exerciseId" TEXT NOT NULL,
    "conceptId" TEXT NOT NULL,
    CONSTRAINT "CourseKnowledgeExerciseBinding_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "CourseKnowledgeExerciseBinding_exerciseId_fkey" FOREIGN KEY ("exerciseId") REFERENCES "CourseKnowledgeExercise" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "CourseKnowledgeExerciseBinding_conceptId_fkey" FOREIGN KEY ("conceptId") REFERENCES "CourseKnowledgeConcept" ("id") ON DELETE CASCADE ON UPDATE CASCADE
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "CourseKnowledgeExerciseBinding_workspaceId_exerciseId_conceptId_role_key" ON "CourseKnowledgeExerciseBinding"("workspaceId", "exerciseId", "conceptId", "role")`,
  `CREATE INDEX IF NOT EXISTS "CourseKnowledgeExerciseBinding_conceptId_role_idx" ON "CourseKnowledgeExerciseBinding"("conceptId", "role")`,
  `CREATE INDEX IF NOT EXISTS "CourseKnowledgeExerciseBinding_exerciseId_idx" ON "CourseKnowledgeExerciseBinding"("exerciseId")`,
  `CREATE TABLE IF NOT EXISTS "CourseKnowledgeMisconception" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "misconceptionKey" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "description" TEXT NOT NULL DEFAULT '',
    "repairHint" TEXT NOT NULL DEFAULT '',
    "severity" REAL NOT NULL DEFAULT 0.5,
    "confidence" REAL NOT NULL DEFAULT 0.55,
    "evidenceJson" TEXT NOT NULL DEFAULT '{}',
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "workspaceId" TEXT NOT NULL,
    "conceptId" TEXT NOT NULL,
    CONSTRAINT "CourseKnowledgeMisconception_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "CourseKnowledgeMisconception_conceptId_fkey" FOREIGN KEY ("conceptId") REFERENCES "CourseKnowledgeConcept" ("id") ON DELETE CASCADE ON UPDATE CASCADE
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "CourseKnowledgeMisconception_workspaceId_conceptId_misconceptionKey_key" ON "CourseKnowledgeMisconception"("workspaceId", "conceptId", "misconceptionKey")`,
  `CREATE INDEX IF NOT EXISTS "CourseKnowledgeMisconception_workspaceId_severity_idx" ON "CourseKnowledgeMisconception"("workspaceId", "severity")`,
  `CREATE TABLE IF NOT EXISTS "CourseKnowledgeActivation" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "activationType" TEXT NOT NULL,
    "sourceType" TEXT NOT NULL,
    "sourceId" TEXT,
    "score" REAL NOT NULL DEFAULT 0.4,
    "evidenceJson" TEXT NOT NULL DEFAULT '{}',
    "activatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "workspaceId" TEXT NOT NULL,
    "conceptId" TEXT NOT NULL,
    CONSTRAINT "CourseKnowledgeActivation_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "CourseKnowledgeActivation_conceptId_fkey" FOREIGN KEY ("conceptId") REFERENCES "CourseKnowledgeConcept" ("id") ON DELETE CASCADE ON UPDATE CASCADE
  )`,
  `CREATE INDEX IF NOT EXISTS "CourseKnowledgeActivation_workspaceId_activatedAt_idx" ON "CourseKnowledgeActivation"("workspaceId", "activatedAt")`,
  `CREATE INDEX IF NOT EXISTS "CourseKnowledgeActivation_conceptId_activatedAt_idx" ON "CourseKnowledgeActivation"("conceptId", "activatedAt")`,
  `CREATE INDEX IF NOT EXISTS "CourseKnowledgeActivation_sourceType_sourceId_idx" ON "CourseKnowledgeActivation"("sourceType", "sourceId")`,
  `CREATE TABLE IF NOT EXISTS "CourseKnowledgeLearnerState" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "stateScope" TEXT NOT NULL DEFAULT 'workspace',
    "masteryEstimate" REAL NOT NULL DEFAULT 0.5,
    "weaknessEstimate" REAL NOT NULL DEFAULT 0.3,
    "readinessEstimate" REAL NOT NULL DEFAULT 0.5,
    "evidenceJson" TEXT NOT NULL DEFAULT '{}',
    "sourceSignalIdsJson" TEXT NOT NULL DEFAULT '[]',
    "status" TEXT NOT NULL DEFAULT 'active',
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "workspaceId" TEXT NOT NULL,
    "conceptId" TEXT NOT NULL,
    CONSTRAINT "CourseKnowledgeLearnerState_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "CourseKnowledgeLearnerState_conceptId_fkey" FOREIGN KEY ("conceptId") REFERENCES "CourseKnowledgeConcept" ("id") ON DELETE CASCADE ON UPDATE CASCADE
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "CourseKnowledgeLearnerState_workspaceId_conceptId_stateScope_key" ON "CourseKnowledgeLearnerState"("workspaceId", "conceptId", "stateScope")`,
  `CREATE INDEX IF NOT EXISTS "CourseKnowledgeLearnerState_workspaceId_readinessEstimate_idx" ON "CourseKnowledgeLearnerState"("workspaceId", "readinessEstimate")`,
  `CREATE INDEX IF NOT EXISTS "CourseKnowledgeLearnerState_workspaceId_weaknessEstimate_idx" ON "CourseKnowledgeLearnerState"("workspaceId", "weaknessEstimate")`,
  `CREATE INDEX IF NOT EXISTS "CourseKnowledgeLearnerState_conceptId_updatedAt_idx" ON "CourseKnowledgeLearnerState"("conceptId", "updatedAt")`,
  `CREATE TABLE IF NOT EXISTS "CourseKnowledgeGovernanceLog" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "action" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'completed',
    "targetType" TEXT NOT NULL,
    "targetId" TEXT,
    "beforeJson" TEXT NOT NULL DEFAULT '{}',
    "afterJson" TEXT NOT NULL DEFAULT '{}',
    "rationale" TEXT NOT NULL DEFAULT '',
    "confidence" REAL NOT NULL DEFAULT 0.55,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "workspaceId" TEXT NOT NULL,
    CONSTRAINT "CourseKnowledgeGovernanceLog_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace" ("id") ON DELETE CASCADE ON UPDATE CASCADE
  )`,
  `CREATE INDEX IF NOT EXISTS "CourseKnowledgeGovernanceLog_workspaceId_action_createdAt_idx" ON "CourseKnowledgeGovernanceLog"("workspaceId", "action", "createdAt")`,
  `CREATE INDEX IF NOT EXISTS "CourseKnowledgeGovernanceLog_targetType_targetId_idx" ON "CourseKnowledgeGovernanceLog"("targetType", "targetId")`
];

export const ensureCourseKnowledgeGraphSchema = async () => {
  for (const statement of statements) {
    await prisma.$executeRawUnsafe(statement);
  }
};
