import prisma from './db';

const statements = [
  `CREATE TABLE IF NOT EXISTS "FlashcardDeck" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "title" TEXT NOT NULL,
    "description" TEXT NOT NULL DEFAULT '',
    "source" TEXT NOT NULL DEFAULT 'ai_studio',
    "sourceFileIds" TEXT NOT NULL DEFAULT '[]',
    "sourceRefsJson" TEXT NOT NULL DEFAULT '[]',
    "settingsJson" TEXT NOT NULL DEFAULT '{}',
    "generationRunId" TEXT,
    "fileObjectId" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "workspaceId" TEXT NOT NULL,
    "workbenchId" TEXT,
    CONSTRAINT "FlashcardDeck_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "FlashcardDeck_workbenchId_fkey" FOREIGN KEY ("workbenchId") REFERENCES "Workbench" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "FlashcardDeck_fileObjectId_fkey" FOREIGN KEY ("fileObjectId") REFERENCES "FileSystemObject" ("id") ON DELETE SET NULL ON UPDATE CASCADE
  )`,
  `CREATE INDEX IF NOT EXISTS "FlashcardDeck_workspaceId_updatedAt_idx" ON "FlashcardDeck"("workspaceId", "updatedAt")`,
  `CREATE INDEX IF NOT EXISTS "FlashcardDeck_workbenchId_idx" ON "FlashcardDeck"("workbenchId")`,
  `CREATE TABLE IF NOT EXISTS "Flashcard" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "front" TEXT NOT NULL,
    "back" TEXT NOT NULL,
    "cardType" TEXT NOT NULL DEFAULT 'basic',
    "difficulty" TEXT NOT NULL DEFAULT 'medium',
    "concept" TEXT NOT NULL DEFAULT '',
    "explanation" TEXT NOT NULL DEFAULT '',
    "tagsJson" TEXT NOT NULL DEFAULT '[]',
    "sourceRefsJson" TEXT NOT NULL DEFAULT '[]',
    "metadataJson" TEXT NOT NULL DEFAULT '{}',
    "orderIndex" INTEGER NOT NULL DEFAULT 0,
    "reviewCount" INTEGER NOT NULL DEFAULT 0,
    "lapseCount" INTEGER NOT NULL DEFAULT 0,
    "dueAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "lastReviewedAt" DATETIME,
    "stability" REAL NOT NULL DEFAULT 0,
    "retrievability" REAL NOT NULL DEFAULT 1,
    "fsrsDifficulty" REAL NOT NULL DEFAULT 5,
    "state" TEXT NOT NULL DEFAULT 'new',
    "suspended" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "workspaceId" TEXT NOT NULL,
    "workbenchId" TEXT,
    "deckId" TEXT NOT NULL,
    CONSTRAINT "Flashcard_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "Flashcard_workbenchId_fkey" FOREIGN KEY ("workbenchId") REFERENCES "Workbench" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "Flashcard_deckId_fkey" FOREIGN KEY ("deckId") REFERENCES "FlashcardDeck" ("id") ON DELETE CASCADE ON UPDATE CASCADE
  )`,
  `CREATE INDEX IF NOT EXISTS "Flashcard_workspaceId_dueAt_idx" ON "Flashcard"("workspaceId", "dueAt")`,
  `CREATE INDEX IF NOT EXISTS "Flashcard_deckId_orderIndex_idx" ON "Flashcard"("deckId", "orderIndex")`,
  `CREATE INDEX IF NOT EXISTS "Flashcard_workbenchId_idx" ON "Flashcard"("workbenchId")`,
  `CREATE TABLE IF NOT EXISTS "FlashcardReviewLog" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "rating" TEXT NOT NULL,
    "elapsedMs" INTEGER NOT NULL DEFAULT 0,
    "previousState" TEXT NOT NULL,
    "nextState" TEXT NOT NULL,
    "previousDueAt" DATETIME,
    "nextDueAt" DATETIME NOT NULL,
    "previousStability" REAL NOT NULL DEFAULT 0,
    "nextStability" REAL NOT NULL DEFAULT 0,
    "previousDifficulty" REAL NOT NULL DEFAULT 5,
    "nextDifficulty" REAL NOT NULL DEFAULT 5,
    "previousRetrievability" REAL NOT NULL DEFAULT 1,
    "nextRetrievability" REAL NOT NULL DEFAULT 1,
    "reviewedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "metadataJson" TEXT NOT NULL DEFAULT '{}',
    "workspaceId" TEXT NOT NULL,
    "cardId" TEXT NOT NULL,
    CONSTRAINT "FlashcardReviewLog_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "FlashcardReviewLog_cardId_fkey" FOREIGN KEY ("cardId") REFERENCES "Flashcard" ("id") ON DELETE CASCADE ON UPDATE CASCADE
  )`,
  `CREATE INDEX IF NOT EXISTS "FlashcardReviewLog_workspaceId_reviewedAt_idx" ON "FlashcardReviewLog"("workspaceId", "reviewedAt")`,
  `CREATE INDEX IF NOT EXISTS "FlashcardReviewLog_cardId_reviewedAt_idx" ON "FlashcardReviewLog"("cardId", "reviewedAt")`,
  `CREATE TABLE IF NOT EXISTS "ConversationSession" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "workspaceId" TEXT NOT NULL,
    "workbenchId" TEXT,
    "userId" TEXT NOT NULL,
    "title" TEXT NOT NULL DEFAULT '',
    "source" TEXT NOT NULL DEFAULT 'terminal',
    "metadataJson" TEXT NOT NULL DEFAULT '{}',
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "ConversationSession_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "ConversationSession_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "ConversationSession_workbenchId_fkey" FOREIGN KEY ("workbenchId") REFERENCES "Workbench" ("id") ON DELETE SET NULL ON UPDATE CASCADE
  )`,
  `CREATE INDEX IF NOT EXISTS "ConversationSession_workspaceId_updatedAt_idx" ON "ConversationSession"("workspaceId", "updatedAt")`,
  `CREATE INDEX IF NOT EXISTS "ConversationSession_userId_updatedAt_idx" ON "ConversationSession"("userId", "updatedAt")`,
  `CREATE TABLE IF NOT EXISTS "ConversationMessage" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "sessionId" TEXT NOT NULL,
    "workspaceId" TEXT NOT NULL,
    "workbenchId" TEXT,
    "userId" TEXT NOT NULL,
    "role" TEXT NOT NULL,
    "content" TEXT NOT NULL,
    "contentHash" TEXT NOT NULL,
    "metadataJson" TEXT NOT NULL DEFAULT '{}',
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "ConversationMessage_sessionId_fkey" FOREIGN KEY ("sessionId") REFERENCES "ConversationSession" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "ConversationMessage_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "ConversationMessage_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "ConversationMessage_workbenchId_fkey" FOREIGN KEY ("workbenchId") REFERENCES "Workbench" ("id") ON DELETE SET NULL ON UPDATE CASCADE
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "ConversationMessage_sessionId_contentHash_key" ON "ConversationMessage"("sessionId", "contentHash")`,
  `CREATE INDEX IF NOT EXISTS "ConversationMessage_workspaceId_createdAt_idx" ON "ConversationMessage"("workspaceId", "createdAt")`,
  `CREATE INDEX IF NOT EXISTS "ConversationMessage_userId_createdAt_idx" ON "ConversationMessage"("userId", "createdAt")`,
  `CREATE INDEX IF NOT EXISTS "ConversationMessage_workspaceId_workbenchId_createdAt_idx" ON "ConversationMessage"("workspaceId", "workbenchId", "createdAt")`,
  `CREATE TABLE IF NOT EXISTS "SavedMemory" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "workspaceId" TEXT NOT NULL,
    "workbenchId" TEXT,
    "userId" TEXT NOT NULL,
    "memoryKey" TEXT NOT NULL,
    "text" TEXT NOT NULL,
    "category" TEXT NOT NULL DEFAULT 'preference',
    "source" TEXT NOT NULL DEFAULT 'explicit_user_request',
    "confidence" REAL NOT NULL DEFAULT 0.9,
    "status" TEXT NOT NULL DEFAULT 'active',
    "createdFromMessageId" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "SavedMemory_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "SavedMemory_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "SavedMemory_workbenchId_fkey" FOREIGN KEY ("workbenchId") REFERENCES "Workbench" ("id") ON DELETE SET NULL ON UPDATE CASCADE
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "SavedMemory_workspaceId_memoryKey_key" ON "SavedMemory"("workspaceId", "memoryKey")`,
  `CREATE INDEX IF NOT EXISTS "SavedMemory_workspaceId_status_updatedAt_idx" ON "SavedMemory"("workspaceId", "status", "updatedAt")`,
  `CREATE TABLE IF NOT EXISTS "LearnerState" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "scope" TEXT NOT NULL DEFAULT 'workspace',
    "version" INTEGER NOT NULL DEFAULT 1,
    "stateJson" TEXT NOT NULL DEFAULT '{}',
    "summary" TEXT NOT NULL DEFAULT '',
    "profileBaseJson" TEXT NOT NULL DEFAULT '{}',
    "knowledgeStateJson" TEXT NOT NULL DEFAULT '{}',
    "misconceptionStateJson" TEXT NOT NULL DEFAULT '{}',
    "preferenceStyleJson" TEXT NOT NULL DEFAULT '{}',
    "behaviorEngagementJson" TEXT NOT NULL DEFAULT '{}',
    "cognitiveStateJson" TEXT NOT NULL DEFAULT '{}',
    "reviewPlanningJson" TEXT NOT NULL DEFAULT '{}',
    "confidenceJson" TEXT NOT NULL DEFAULT '{}',
    "lastEvidenceAt" DATETIME,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "workspaceId" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    CONSTRAINT "LearnerState_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "LearnerState_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "LearnerState_workspaceId_scope_key" ON "LearnerState"("workspaceId", "scope")`,
  `CREATE INDEX IF NOT EXISTS "LearnerState_userId_updatedAt_idx" ON "LearnerState"("userId", "updatedAt")`,
  `CREATE INDEX IF NOT EXISTS "LearnerState_workspaceId_updatedAt_idx" ON "LearnerState"("workspaceId", "updatedAt")`,
  `CREATE TABLE IF NOT EXISTS "LearnerStateVersion" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "version" INTEGER NOT NULL,
    "stateJson" TEXT NOT NULL DEFAULT '{}',
    "summary" TEXT NOT NULL DEFAULT '',
    "changedBy" TEXT NOT NULL DEFAULT 'system',
    "changeReason" TEXT NOT NULL DEFAULT '',
    "patchIdsJson" TEXT NOT NULL DEFAULT '[]',
    "evidenceIdsJson" TEXT NOT NULL DEFAULT '[]',
    "confidenceJson" TEXT NOT NULL DEFAULT '{}',
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "workspaceId" TEXT NOT NULL,
    "learnerStateId" TEXT NOT NULL,
    CONSTRAINT "LearnerStateVersion_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "LearnerStateVersion_learnerStateId_fkey" FOREIGN KEY ("learnerStateId") REFERENCES "LearnerState" ("id") ON DELETE CASCADE ON UPDATE CASCADE
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "LearnerStateVersion_learnerStateId_version_key" ON "LearnerStateVersion"("learnerStateId", "version")`,
  `CREATE INDEX IF NOT EXISTS "LearnerStateVersion_workspaceId_createdAt_idx" ON "LearnerStateVersion"("workspaceId", "createdAt")`,
  `CREATE TABLE IF NOT EXISTS "LearnerEvidence" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "evidenceType" TEXT NOT NULL,
    "sourceType" TEXT NOT NULL,
    "sourceId" TEXT,
    "actor" TEXT NOT NULL DEFAULT 'system',
    "title" TEXT NOT NULL DEFAULT '',
    "summary" TEXT NOT NULL DEFAULT '',
    "payloadJson" TEXT NOT NULL DEFAULT '{}',
    "confidence" REAL NOT NULL DEFAULT 0.6,
    "observedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "workspaceId" TEXT NOT NULL,
    "workbenchId" TEXT,
    "goalId" TEXT,
    CONSTRAINT "LearnerEvidence_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "LearnerEvidence_workbenchId_fkey" FOREIGN KEY ("workbenchId") REFERENCES "Workbench" ("id") ON DELETE SET NULL ON UPDATE CASCADE
  )`,
  `CREATE INDEX IF NOT EXISTS "LearnerEvidence_workspaceId_observedAt_idx" ON "LearnerEvidence"("workspaceId", "observedAt")`,
  `CREATE INDEX IF NOT EXISTS "LearnerEvidence_workspaceId_evidenceType_observedAt_idx" ON "LearnerEvidence"("workspaceId", "evidenceType", "observedAt")`,
  `CREATE INDEX IF NOT EXISTS "LearnerEvidence_sourceType_sourceId_idx" ON "LearnerEvidence"("sourceType", "sourceId")`,
  `CREATE TABLE IF NOT EXISTS "LearnerStatePatch" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "status" TEXT NOT NULL DEFAULT 'pending',
    "proposedBy" TEXT NOT NULL DEFAULT 'system',
    "targetDimension" TEXT NOT NULL,
    "operation" TEXT NOT NULL,
    "confidence" REAL NOT NULL DEFAULT 0.6,
    "payloadJson" TEXT NOT NULL DEFAULT '{}',
    "rationale" TEXT NOT NULL DEFAULT '',
    "appliedVersion" INTEGER,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "appliedAt" DATETIME,
    "workspaceId" TEXT NOT NULL,
    "workbenchId" TEXT,
    "learnerStateId" TEXT,
    "evidenceId" TEXT,
    CONSTRAINT "LearnerStatePatch_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "LearnerStatePatch_workbenchId_fkey" FOREIGN KEY ("workbenchId") REFERENCES "Workbench" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "LearnerStatePatch_learnerStateId_fkey" FOREIGN KEY ("learnerStateId") REFERENCES "LearnerState" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "LearnerStatePatch_evidenceId_fkey" FOREIGN KEY ("evidenceId") REFERENCES "LearnerEvidence" ("id") ON DELETE SET NULL ON UPDATE CASCADE
  )`,
  `CREATE INDEX IF NOT EXISTS "LearnerStatePatch_workspaceId_status_createdAt_idx" ON "LearnerStatePatch"("workspaceId", "status", "createdAt")`,
  `CREATE INDEX IF NOT EXISTS "LearnerStatePatch_learnerStateId_status_idx" ON "LearnerStatePatch"("learnerStateId", "status")`,
  `CREATE INDEX IF NOT EXISTS "LearnerStatePatch_evidenceId_idx" ON "LearnerStatePatch"("evidenceId")`,
  `CREATE TABLE IF NOT EXISTS "LearnerMemoryControl" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "workspaceId" TEXT NOT NULL,
    "workbenchId" TEXT,
    "memoryKey" TEXT NOT NULL,
    "dimension" TEXT NOT NULL,
    "action" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'active',
    "originalText" TEXT NOT NULL DEFAULT '',
    "correctedText" TEXT NOT NULL DEFAULT '',
    "reason" TEXT NOT NULL DEFAULT '',
    "weightMultiplier" REAL NOT NULL DEFAULT 1,
    "createdBy" TEXT NOT NULL DEFAULT 'user',
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "LearnerMemoryControl_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "LearnerMemoryControl_workbenchId_fkey" FOREIGN KEY ("workbenchId") REFERENCES "Workbench" ("id") ON DELETE SET NULL ON UPDATE CASCADE
  )`,
  `CREATE INDEX IF NOT EXISTS "LearnerMemoryControl_workspaceId_status_idx" ON "LearnerMemoryControl"("workspaceId", "status")`,
  `CREATE INDEX IF NOT EXISTS "LearnerMemoryControl_workspaceId_memoryKey_idx" ON "LearnerMemoryControl"("workspaceId", "memoryKey")`,
  `CREATE INDEX IF NOT EXISTS "LearnerMemoryControl_workspaceId_dimension_idx" ON "LearnerMemoryControl"("workspaceId", "dimension")`
];

export const ensureLearningStateSchema = async () => {
  for (const statement of statements) {
    await prisma.$executeRawUnsafe(statement);
  }
};
